### ISSUE TITLE
When will the code be made public

### ISSUE THREAD

**Issue by Yueming-Yin** [MinkaiXu/GeoLDM#1]
Hi, Minkai. Great work, when will the code for the work be made public?

**Comment by MinkaiXu** [comment]
Hi Yueming. Thanks for your interest, and sorry that busy with NeurIPS these days. Would provide it after NeurIPS deadline. Thanks!

**Comment by pearl-rabbit** [comment]
Hello, I apologize for bothering you. I would like to ask, will the code be updated in the near future?

**Comment by MinkaiXu** [comment]
Sorry for the delay. I rushed the release today and you can take a look! @Yueming-Yin @pearl-rabbit

**Comment by pearl-rabbit** [comment]
Thank you for sharing.
